package gov.mea.psp.instantApps.util;

public class InstantAppConstants {
	
	public static final String[] AUDITPERIODVALUES = { "Jan-Mar14",
			"Apr-Jun14", "Jul-Sep14", "Oct-Dec14", "Jan-Mar15", "Apr-Jun15",
			"Jul-Sep15", "Oct-Dec15", "Apr-June16", "July-Sep16", "Oct-Dec16",
			"Jan-Mar16", "Apr-Jun16", "Jul-Sep16", "Oct-Dec16", "Jan-Mar17",
			"Apr-Jun17", "Jul-Sep17", "Oct-Dec17", "Apr-Jun18", "Jul-Sep18",
			"Oct-Dec18", "Jan-Mar19", "Apr-Jun19", "Jul-Sep19", "Oct-Dec19",
			"Jan-Mar20", "Apr-Jun20", "Jul-Sep20", "Oct-Dec20" };
	 
	public static final String[] AUDITSTATUSVALUES = { "Scheduled", "Conducted", "Draft report Submitted",
			"Report Finalized" };

	public static final String[] ENTITYVALUES = { "Central Support Team", "CPPF", "CPV Delhi (Mgmt Functions)",
			"Data Centre", "Data Recovery Centre",
			"Passport Seva Back Office (Logical Entity for Depiction of Hierarchy)", "PSK Alappuzha",
			"PSK Aluva (Ernakulam)", "PSK Ambala", "PSK Ameerpet (Hyderabad-2)", "PSK Aminjikarai (Chennai-2)",
			"PSK Amritsar", "PSK Andheri (Mumbai-2)", "PSK Bangalore, Lalbagh", "PSK Bangalore, Sai Arcade",
			"PSK Bareilly", "PSK Begumpet (Hyderabad-1)", "PSK Berhampore", "PSK Bhopal", "PSK Bhubaneswar",
			"PSK Chandigarh", "PSK Chandigarh-II (Chandigarh Extn)", "PSK Coimbatore", "PSK Dehradun", "PSK Ghaziabad",
			"PSK Gorakhpur", "PSK Gurgaon", "PSK Guwahati", "PSK Herald House - ITO (Delhi-1)", "PSK Hoshiarpur",
			"PSK Hubli", "PSK Jaipur", "PSK Jalandhar-1 (Eminent Mall)", "PSK Jalandhar-2 (Aman's Plaza)", "PSK Jammu",
			"PSK - Jodhpur", "PSK Kannur (Kannur-1)", "PSK Kanpur", "PSK Kolkata", "PSK Kollam", "PSK Kottayam",
			"PSK Kozhikode (Kozhikode-1)", "PSK Lower Parel (Mumbai-3)", "PSK Lucknow", "PSK Ludhiana", "PSK Madurai",
			"PSK Malad (Mumbai-1)", "PSK Malappuram", "PSK Mangalore", "PSK Mithakali Ahmedabad", "PSK Nagpur",
			"PSK Nashik", "PSK Neyyattinkara, Trivandrum (Rural)", "PSK Nizamabad", "PSK Panaji", "PSK Patna",
			"PSK Payyanur, Kannur (Kannur-2)", "PSK Pune", "PSK R K Puram (Bikaji Cama Place)", "PSK Raipur",
			"PSK Rajkot", "PSK Ranchi", "PSK Saligramam (Chennai-1)", "PSK Shalimar Place (Delhi-2)", "PSK Shimla",
			"PSK Sikar", "PSK Srinagar", "PSK Surat", "PSK Tambaram (Chennai-3)", "PSK Thane", "PSK Thanjavur",
			"PSK Thrissur", "PSK Tirunelveli City", "PSK Tirupathi", "PSK Toli Chowki (Hyderabad-3)", "PSK Trichy",
			"PSK Tripunithura, Cochin", "PSK Vadakara, Kozhikode (Kozhikode 2)", "PSK Vadodara", "PSK Vadodara-II",
			"PSK Varanasi", "PSK Vazhuthacaud, Trivandrum (Urban)", "PSK Vijay Cross Road Ahmedabad", "PSK Vijayawada",
			"PSK Vijayawada-II", "PSK Visakhapatnam (Vizag)", "PSP Application", "PSP Business Operations",
			"PSP Program", "PSP Testing & Assurance", "RPO Ahmedabad", "RPO Amritsar", "RPO Bangalore", "RPO Bareilly",
			"RPO Bhopal", "RPO Bhubaneswar", "RPO Chandigarh", "RPO Chennai", "RPO Cochin", "RPO Coimbatore",
			"RPO Dehradun", "RPO Delhi", "RPO Ghaziabad", "RPO Goa", "RPO Guwahati", "RPO Hyderabad", "RPO Jaipur",
			"RPO Jalandhar", "RPO Jammu", "RPO Kolkata", "RPO Kozhikode", "RPO Lucknow", "RPO Madurai",
			"RPO Malappuram", "RPO Mumbai", "RPO Nagpur", "RPO Patna", "RPO Pune", "RPO Raipur", "RPO Ranchi",
			"RPO Shimla", "RPO Srinagar", "RPO Surat", "RPO Thane", "RPO Trichy", "RPO Trivandrum",
			"RPO Visakhapatnam" };

	public static final String[] NCRSTATUSVALUES = { "Open", "In Progress", "Closed", "Re-Open", "Verified" };
	
	public static final String[] MODEOFAUDITVALUES = { "Face to Face", "Telecon", "Checklist" };
	
	public static final String[] ISO270012013VALUES = { " A.6.2.2-Teleworking", "A.6.2.1-Mobile device policy",
			"A.6.1.5-Information security in project management", "A.6.1.4-Contact with special interest groups",
			"A.6.1.3-Contact with authorities", "A.6.1.2-Segregation of duties",
			"A.6.1.1-Information security roles and responsibilities",
			"A.5.1.2-Review of the policies for information security", "A.5.1.1-Policies for information security",
			"A.7.1.1-Screening", "A.7.1.2-Terms and conditions of employment", "A.7.2.1-Management responsibilities",
			"A.7.2.2-Information security awareness, education and training", "A.7.2.3-Disciplinary process",
			"A.7.3.1-Termination or change of employment responsibilities", "A.8.1.1-Inventory of assets",
			"A.8.1.2-Ownership of assets", "A.8.1.3-Acceptable use of assets", "A.8.1.4-Return of assets",
			"A.8.2.1-Classification of information", "A.8.2.2-Labelling of information", "A.8.2.3-Handling of assets",
			"A.8.3.1-Management of removable media", "A.8.3.2-Disposal of media", "A.8.3.3-Physical media transfer",
			"A.9.1.1-Access Control policy", "A.9.1.2-Access to networks and network services",
			"A.9.2.1-User registration and de-registration", "A.9.2.2-User access provisioning",
			"A.9.2.3-Management of privileged access rights",
			"A.9.2.4-Management of secret authentication information of users", "A.9.2.5-Review of user access rights",
			"A.9.2.6-Removal or adjustment of access rights", "A.9.3.1-Use of secret authentication information",
			"A.9.4.1-Information access restriction", "A.9.4.2-Secure log-on procedures",
			"A.9.4.3-Password management system", "A.9.4.4-Use of privileged utility programs",
			"A.9.4.5-Access control to program source code", "A.10.1.1-Policy on the use of cryptographic controls",
			"A.10.1.2-Key management", "A.11.1.1-Physical security perimeter", "A.11.1.2-Physical entry controls",
			"A.11.1.3-Securing offices, rooms and facilities",
			"A.11.1.4-Protecting against external and environmental threats", "A.11.1.5-Working in secure areas",
			"A.11.1.6-Delivery and loading areas", "A.11.2.1-Equipment sitting and protection",
			"A.11.2.2-Supporting utilities", "A.11.2.3-Cabling security", "A.11.2.4-Equipment maintenance",
			"A.11.2.5-Removal of assets", "A.11.2.6-Security of equipment and assets off-premises",
			"A.11.2.7-Secure disposal or reuse of equipment", "A.11.2.8-Unattended user equipment",
			"A.11.2.9-Clear desk and clear screen policy", "A.12.1.1-Documented operating procedures",
			"A.12.1.2-Change management", "A.12.1.3-Capacity management",
			"A.12.1.4-Separation of development, testing and operational environments",
			"A.12.2.1-Controls against malware", "A.12.4.1-Event logging", "A.12.4.2-Protection of log information",
			"A.12.4.3-Administrator and operator logs", "A.12.4.4-Clock synchronisation",
			"A.12.5.1-Installation of software on operational systems",
			"A.12.6.1-Management of technical vulnerabilities", "A.12.6.2-Restrictions on software installation",
			"A.12.7.1-Information systems audit controls", "A.13.1.1-Network controls",
			"A.13.1.2-Security of network services", "A.13.1.3-Segregation in networks",
			"A.13.2.1-Information transfer policies and procedures", "A.13.2.2-Agreements on information transfer",
			"A.13.2.3-Electronic messaging", "A.13.2.4-Confidentiality or non-disclosure agreements",
			"A.14.1.1-Information security requirements analysis and specification",
			"A.14.1.2-Securing application services on public networks",
			"A.14.1.3-Protecting application services transactions", "A.14.2.1-Secure development policy",
			"A.14.2.2-System change control procedures",
			"A.14.2.3-Technical review of applications after operating platform changes",
			"A.14.2.4-Restrictions on changes to software packages", "A.14.2.5-Secure system engineering principles",
			"A.14.2.6-Secure development environment", "A.14.2.7-Outsourced development",
			"A.14.2.8-System security testing", "A.14.2.9-System acceptance testing",
			"A.14.3.1-Protection of test data", "A.15.1.1-Information security policy for supplier relationships",
			"A.15.1.2-Addressing security within supplier agreements",
			"A.15.1.3-Information and communication technology supply chain",
			"A.15.2.1-Monitoring and review of supplier services", "A.15.2.2-Managing changes to supplier services",
			"A.16.1.1-Responsibilities and procedures", "A.16.1.2-Reporting information security events",
			"A.16.1.3-Reporting information security weaknesses",
			"A.16.1.4-Assessment of and decision on information security events",
			"A.16.1.5-Response to information security incidents",
			"A.16.1.6-Learning from information security incidents", "A.16.1.7-Collection of evidence",
			"A.17.1.1-Planning information security continuity",
			"A.17.1.2-Implementing information security continuity",
			"A.17.1.3-Verify, review and evaluate information security continuity",
			"A.17.2.1-Availability of information processing facilities",
			"A.18.1.1-Identification of applicable legislation and contractual requirements",
			"A.18.1.2-Intellectual property rights", "A.18.1.3-Protection of records",
			"A.18.1.4-Privacy and protection of personally identifiable information",
			"A.18.1.5-Regulation of cryptographic controls", "A.18.2.1-Independent review of information security",
			"A.18.2.2-Compliance with security policies and standards", "A.18.2.3-Technical compliance review" };

	public static final String[] NAMEOFAUDITORVALUES = { "auditor", "Chandrakant Silveni", "Deepak Nagaraj, RH",
			"Dilip P", "Dinesh Kumar Singri", "Gopal Sharma", "Harmeet Kaur", "Indranil Chatterjee", "K V Mukunda Rao",
			"Laxminarayana Chinta", "Manish Saxena", "Neeraj Kumar", "Nikhil Saurabh", "Nirav Shah", "Nitin Khambe",
			"P Dilip, RH", "Padma Nagaraj", "Prasenjit Das", "Prashant Pandey", "PRATAP CHANDRA NANDA", "Priti Thareja",
			"PSP0245", "PSP02672", "psp0304", "PSP0573", "PSP0585", "PSP0703", "PSP0712", "PSP0726", "psp0801",
			"PSP0948", "PSP1014", "PSP1094", "PSP1246", "PSP1269", "PSP1334", "PSP1369", "PSP1409", "psp1497",
			"PSP1572", "PSP1629", "PSP1842", "PSP1920", "PSP1990", "PSP1992", "PSP2281", "PSP2332", "PSP2337",
			"PSP2394", "PSP2396", "PSP2423", "PSP2425", "psp2442", "PSP2454", "PSP2457", "PSP2458", "PSP2461",
			"PSP2474", "PSP2498", "PSP2502", "PSP2509", "PSP2515", "PSP2565", "PSP2577", "PSP2596", "PSP2598",
			"PSP2627", "PSP2668", "PSP2721", "PSP2722", "PSP2768", "PSP2769", "psp2782", "PSP2783", "PSP2805",
			"psp2828", "PSP2833", "PSP2839", "PSP2860", "PSP2869", "PSP2876", "PSP2975", "PSP2981", "psp3070",
			"PSP3074", "psp3140", "psp3234", "PSP3538", "PSP3733", "Rajesh Gaira", "Ranjit Kumar", "Rashmi Shrivastava",
			"Rashmi, CH", "Rishi Kapoor", "Roopa", "RPO_Amritsar", "RPO_Bareilly", "RPO_Bhopal", "RPO_Cochin",
			"RPO_Coimbatore", "RPO_Dehradun", "RPO_Jalandhar", "RPO_Kolkata", "RPO_Kozhikode", "RPO_Patna",
			"RPO_Raipur", "RPO_Surat", "RPO_Thane", "RPO_Trivendrum", "S K Mutreja", "Santanu Bhattacharya",
			"Satish Dubey", "Shalini Manchanda", "Shelly Srivastava", "SUBHENDU BIKASH SEAL", "Surya",
			"Surya Prakash Dixit", "Suryaprakashdixit", "Swapnil Sanadhya", "Umesh Nair", "V Swaminathan",
			"Vaishali Singhi", "Yukti Katyal", "Yukti Katyal, CH" };
	
	public static final String[] ISO90012008VALUES = { "4.1 - Quality Management System - General Requirements",
			"4.2 - Documentation Requirements", "5.1 - Management Commitment", "5.2 - Customer Focus",
			"5.3 - Quality Policy", "5.4 - Planning", "5.5 - Responsibility, Authority & Communication",
			"5.6 - Management Review", "6.1 - Provision of Resources-QMS", "6.2 - Human Resources",
			"6.3 - Infrastructure", "6.4 - Work Environment", "7.1 - Planning for Product Realisation",
			"7.2 - Customer Related Processes", "7.3 - Design & Development", "7.4 - Purchasing",
			"7.5 - Production & Service Provision", "7.6 - Control of monitoring & measurement equipment",
			"8.1 - Measurement Analysis & Improvement ? General", "8.2 - Monitoring & Measurement",
			"8.3 - Control of Non-conforming product", "8.4 - Analysis of Data", "8.5 - Improvement" };
	
	public static final String[] COLUMNNAMES = { "S. No.", "Audit Reference Number", "Audit Period", "Audit Status",
			"Mode of Audit", "View Report" };
}
